#participants_tsv: 'config/participants/hcp7T_participants.tsv'
participants_tsv: 'config/participants/hcptest_participants.tsv' # Test participants

# Singularity containers
singularity:
  neuroglia: /project/6050199/akhanf/singularity/bids-apps/khanlab_neuroglia-core_latest.sif
  freesurfer: /project/6050199/akhanf/singularity/bids-apps/khanlab_freesurfer_v6.0.1-subfields.img
  connectome_workbench: /project/6050199/akhanf/singularity/bids-apps/khanlab_connectome-workbench_latest.sif
  fsl_cuda: /project/6050199/akhanf/singularity/bids-apps/fsl_6.0.3_cuda9.1.sif

# Freesurfer license:
fs_license: /project/6050199/akhanf/opt/freesurfer/.license

##### INPUT PATHS / VARIABLES #####
# Subject freesurfer directory (with surf/ and mri/ subdirectories)
# Uses subject wildcard
freesurfer:
  subject: 'freesurfer/sub-{subject}'
  root: 'freesurfer'
  tar: /project/6050199/ext-data/hcp1200/HCP_1200_T1w_Diffusion_FS/{subject}/T1w/{subject}.freesurfer.tar

# Template
template: MNI152NLin6Asym

# Transforms
transforms:
  subject: 'hcp/sub-{subject}'
  zip: /project/6050199/ext-data/hcp1200/zipfiles/{subject}_3T_Structural_preproc.zip
  root: 'hcp'
  warp: 'standard2acpc_dc.nii.gz' # To subject
  invwarp: 'acpc_dc2standard.nii.gz' # To template
  ref_nii: 'resources/standard_atlases/tpl-MNI152NLin6Asym-res-04_desc-brain_T1w.nii.gz'

# Segmentation threshold
prob_seg_threshold: 0.5

# Seed segmentations
seed:
  dir: /scratch/tkai/zona/misc/zona_parcellations/MIN152NLin6Asym
  nii: sub-SNSXNLin2020Asym_space-MNI152NLin6Asym_hemi-{hemi}_desc-{seed}_prob.nii.gz
  structures:
    ZI: ZI
    # cZI: cZI
    # rZI: rZI

# Target segmentations
target:
  cortical:
    tsv: resources/label-hcpmmp180_dseg.tsv
    atlas: hcpmmp180 # must be [a-zA-Z0-9]+

# Bedpost params
bedpost:
  dir: /project/6050199/ext-data/hcp1200/HCP_1200_T1w_Diffusion_FS
  samples: '{subject}/T1w/Diffusion_7T.bedpostX/meanS0samples.nii.gz'
  merged_prefix: '{subject}/T1w/Diffusion_7T.bedpostX/merged'

# Max no. of clusters (will perform with k=range(2,max_k+1))
max_k: 8

# Tractography parameters
probtrack:
    seed_resolution: 1.0
    res_name: dwi # bids deriv filename will have res-{res_name}
    nsamples: 10000
    opts: '--loopcheck --onewaycondition --cthr=0.2 --nsteps=2000 --steplength=0.5  --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd --os2t --randfib=2' 

probtrack_tractmap:
    seed_resolution: 0.5
    res_name: super #bids deriv filename will have res-{res_name}
    nsamples: 1000
    opts: '--loopcheck --onewaycondition --cthr=0.2 --nsteps=2000 --steplength=0.5  --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd --randfib=2' 
