
participants_tsv: 'config/middle1participants.tsv'


#singularity containers:
singularity:
  neuroglia: /project/6050199/akhanf/singularity/bids-apps/khanlab_neuroglia-core_latest.sif
  freesurfer: /project/6050199/akhanf/singularity/bids-apps/khanlab_freesurfer_v6.0.1-subfields.img
  connectome_workbench: /project/6007967/software/transparentsingularity/connectome-workbench_1.4.1_20191117.simg/connectome-workbench_1.4.1_20191117.simg 

#path to your freesurfer license file:
fs_license: /project/6050199/akhanf/opt/freesurfer/.license



#set-up paths to inputs here:


#path to subject freesurfer dir (containing surf/ and mri/ subfolders) 
# use the {subject} wildcard here.. 

in_freesurfer: /scratch/sudesnac/CamCAN/freesurfer/sub-{subject}



template_prob_seg: 
  fullBF: 'resources/CamCAN_middle1_fullBF_B.nii.gz'

#to apply to masks in target space before tracking, and template-space before grouping..
prob_seg_threshold: 0.5


template: CamCANmiddle1
ants_affine_mat: /scratch/sudesnac/CamCAN/camcan_template/results/cohort-middle1/iter_8/sub-{subject}_0GenericAffine.mat
ants_invwarp_nii: /scratch/sudesnac/CamCAN/camcan_template/results/cohort-middle1/iter_8/sub-{subject}_1InverseWarp.nii.gz
ants_warp_nii: /scratch/sudesnac/CamCAN/camcan_template/results/cohort-middle1/iter_8/sub-{subject}_1Warp.nii.gz
ants_ref_nii: /scratch/sudesnac/CamCAN/camcan_template/results/cohort-middle1/iter_8/template_T1w.nii.gz

#list of ROIs in target segmentations 
targets_dseg_tsv: resources/label-hcpmmp180_dseg.tsv
targets_atlas_name: hcpmmp180 #must be [a-zA-Z0-9]+

#bedpost
fsl_bedpost_dir: /project/6050199/akhanf/ext-bids/cam-can/deriv/snakedwi/results
bedpost_mean_s0_samples: 'sub-{subject}/dwi/sub-{subject}_space-T1w_res-orig_desc-eddy_diffusion.bedpostX/mean_S0samples.nii.gz'
bedpost_merged_prefix: 'sub-{subject}/dwi/sub-{subject}_space-T1w_res-orig_desc-eddy_diffusion.bedpostX/merged'

#maximum number of clusters in spectral clustering
# will perform with k=range(2,max_k+1)
max_k: 8


#tractography parameters
probtrack:
    seed_resolution: 1.0
    res_name: dwi # bids deriv filename will have res-{res_name}

    nsamples: 10000
    opts: '--loopcheck --onewaycondition --cthr=0.2 --nsteps=2000 --steplength=0.5  --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd --os2t --randfib=2' 


probtrack_tractmap:
    seed_resolution: 0.5
    res_name: super #bids deriv filename will have res-{res_name}
    nsamples: 1000
    opts: '--loopcheck --onewaycondition --cthr=0.2 --nsteps=2000 --steplength=0.5  --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd --randfib=2' 






